# Generated by Django 4.0.6 on 2022-09-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0002_artista_obradearte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='Estilo',
            new_name='estilo',
        ),
        migrations.RenameField(
            model_name='obradearte',
            old_name='Estilo',
            new_name='estilo',
        ),
        migrations.AlterField(
            model_name='obradearte',
            name='anio',
            field=models.IntegerField(),
        ),
    ]
